### ISSUE TITLE
Question: Is there any reason why you are not support IE?

### ISSUE THREAD

**Issue by dmitry-dedukhin** [wmluke/angular-flash#19] opened 2013-11-05 12:26 UTC
Hi!

A quick search for IE's Object.defineProperty polyfill gives me nothing (i.e. there is no good polyfill).
So, I've created [fork](https://github.com/dmitry-dedukhin/angular-flash) with fixes for IE. Fixes are trivial - all setters are replaced by function calls.
I know that this is breaking changes, is there any chance that this fix will be accepted by you?

**Comment by wmluke** [comment] 2013-11-05 21:42
Hi @dmitry-dedukhin,

Thanks for the feature request.  

`Object.defineProperty` is supported by IE9 and above.  IE8 only supports it on DOM objects.  IE7 and below do not support it.

At this time, I'm not so enthused to support IE8 and below, but I'll leave this feature request open for a while to see how many other folks need it.

References:
- http://kangax.github.io/es5-compat-table/
- http://stackoverflow.com/questions/10282075/object-defineproperty-for-all-browsers

Thanks again,
Luke

**Comment by wmluke** [comment] 2013-11-05 21:44
Lol. Accidentally, hit "Close & Comment".  Reopened.

**Comment by dmitry-dedukhin** [comment] 2013-11-06 07:33
Yep, I understand your point of view.
According to [statistics](http://www.w3schools.com/browsers/browsers_explorer.asp) there are about 4.7% of IE<=8. And this percent becomes lower each day.
But since I'm using angular-flash in enterprise-level application I should provide at least correct behavior in IE<=8. And the current code of angular-flash breaks my application at all in old IE's.

I can live with the own fork but may be other people (as you said) needs this feature too...

**Comment by wmluke** [comment] 2014-01-24 19:29
Don't see much need from anyone else. Closing.

**Closed as completed by wmluke** 2014-01-24 19:29 UTC
Labels: enhancement

**Comment by austinpray** [comment] 2014-08-05 23:54
Angular 1.2 is verified against ie8. This is the only module in my entire app that breaks compatibility with ie8. I am going to go ahead and use @dmitry-dedukhin 's fork because I am on a time-crunch, but I am definitely going to circle around and see if I can get a pull request in. The issue is that it should at least not throw a JS error when not working with ie8.
